name = "cache-cleanup"
main = "src/index.ts"
compatibility_date = "2022-08-31"

[triggers]
crons = [ "0 12 */1 * *" ]

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'overlays'
preview_bucket_name = "overlays"
